# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admini',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='admini',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='admini',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
