# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-09 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='praise',
            field=models.FloatField(default=100),
        ),
    ]
