# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20191104_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admini',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Admini',
        ),
    ]
