# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20191104_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='url_name',
            new_name='reverse_name',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
