# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20191104_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
                ('telephone', models.IntegerField(blank=True, null=True, verbose_name='电话号码')),
                ('roles', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rbac.Role', verbose_name='职位')),
            ],
        ),
    ]
