# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(default=2, to='rbac.Role', verbose_name='职位'),
        ),
    ]
