# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-25 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_permission_role_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissons',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
