# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='H1.Article', verbose_name='文章'),
        ),
    ]
