# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20191019_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuses',
            options={'verbose_name': '校区表', 'verbose_name_plural': '校区表'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
