# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-02 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20191102_1112'),
        ('sales', '0004_auto_20191022_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
