# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20191103_2114'),
        ('sales', '0002_auto_20191022_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role'),
        ),
    ]
