# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191105_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='web.Tag', verbose_name='标签'),
        ),
    ]
