# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-09 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('imgs', models.CharField(max_length=255, verbose_name='图片')),
                ('category', models.IntegerField(choices=[(1, '经验'), (2, '技术'), (3, '杂谈'), (4, '感悟')], default=1, verbose_name='文章分类')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '发布'), (2, '删除')], default=1, verbose_name='状态')),
                ('scan', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment_count', models.IntegerField(verbose_name='评论数')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('articles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='V1.Article', verbose_name='所属文章')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=1, verbose_name='评论内容')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V1.Article', verbose_name='所属文章')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='图片名称')),
                ('url', models.ImageField(max_length=255, upload_to='', verbose_name='图片路径')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V1.Article', verbose_name='所属文章')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='权限名')),
                ('url', models.CharField(max_length=32, verbose_name='路径')),
                ('url_name', models.CharField(max_length=64, verbose_name='别名')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='身份')),
                ('permissions', models.ManyToManyField(to='V1.Permission', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V1.Role', verbose_name='身份')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V1.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='V1.User', verbose_name='作者'),
        ),
    ]
