# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-09 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='别名'),
        ),
    ]
