# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0004_auto_20191109_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='V1.Comment', verbose_name='回复'),
        ),
    ]
