# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-15 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('V1', '0005_comment_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
