# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-17 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_authordetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
