"""
Django settings for huolala project.

Generated by 'django-admin startproject' using Django 1.11.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bac#rb-f_07sna!(q4lk&g35q)10x(i*i3j*!2a=xb)($7)otn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'H1.apps.H1Config',
    'S1.apps.S1Config',
    'V1.apps.V1Config',
    'V2.apps.V2Config',
    "rest_framework",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'huolala.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huolala.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'H1',
        'USER': 'root',
        'PASSWORD': '666',
        'HOST': '127.0.0.1',
        'PORT': 3306,

    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'statics')
]


REST_FRAMEWORK={
    # 分页部分
    "PAGE_SIZE":2,  #将分页限制加入配置文件
    "DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination", # 将默认分页类加入到配置文件中，作为全局变量，个别函数如果需要，则自己定制覆盖
    # 版本部分
    # "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # "ALLOWED_VERSIONS": ['v1', 'v2'],
    # 'VERSION_PARAM': 'version',
    # # 认证部分
    "DEFAULT_AUTHENTICATION_CLASSES": ["V1.utils.aaa.Authentication", ],
    "DEFAULT_UNAUTHENTICATION_CLASSES": ["V1.utils.aaa.AnnoyAuthentication", ],
    "UNAUTHENTICATED_USER": None,
    "UNAUTHENTICATED_TOKEN": None,
    # 权限部分
    "DEFAULT_PERMISSION_CLASSES": ["V1.utils.aaa.Permission", ],
    # 节流
    # "DEFAULT_Throttle_CLASSES": ["V1.utils.aaa.Permission", ],
    "DEFAULT_THROTTLE_CLASSES": ["V1.utils.aaa.RateThrottle", ],
    "DEFAULT_THROTTLE_RATES": {"anon": '3/m'}
}

# {"category":"2","content":"bbbb","title":"ffffff","comment_count":4,"author":2}


import datetime
JWT_AUTH={"JWT_EXPIRATION_DELTA":datetime.timedelta(minutes=10)}