# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('check', models.IntegerField(verbose_name='浏览数量')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('photo', models.ImageField(upload_to=None, verbose_name='文章图片')),
                ('article_status', models.IntegerField(choices=[(1, '发布'), (2, '删除')], default=1, verbose_name='文章状态')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('content_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('zan', models.IntegerField(verbose_name='点赞数')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hulaquan.Article', verbose_name='关联文章')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标签')),
                ('tid', models.IntegerField(unique=True, verbose_name='标签ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hulaquan.Tag', to_field='tid', verbose_name='关联标签'),
        ),
    ]
