# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='IP地址')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=32, verbose_name='slot')),
                ('capacity', models.CharField(max_length=32, verbose_name='capacity')),
                ('model', models.CharField(max_length=32, verbose_name='model')),
                ('speed', models.CharField(max_length=32, verbose_name='speed')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='manufacturer')),
                ('sn', models.CharField(max_length=32, verbose_name='sn')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='ip')),
            ],
        ),
    ]
