# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191116_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=32, verbose_name='制造商')),
                ('sn', models.CharField(max_length=255, verbose_name='sn')),
                ('model', models.CharField(max_length=255, verbose_name='型号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='主机')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=32, verbose_name='处理器')),
                ('cpu_family', models.CharField(max_length=255, verbose_name='cpu_family')),
                ('cpu_cores', models.CharField(max_length=255, verbose_name='cpu_cores')),
                ('cache_size', models.CharField(max_length=255, verbose_name='cache_size')),
                ('clflush_size', models.CharField(max_length=255, verbose_name='clflush_size')),
                ('model', models.CharField(max_length=255, verbose_name='型号')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='主机')),
            ],
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('up', models.BooleanField(verbose_name='up')),
                ('hwaddr', models.CharField(max_length=255, verbose_name='hwaddr')),
                ('address', models.CharField(max_length=32, verbose_name='address')),
                ('netmask', models.CharField(max_length=32, verbose_name='netmask')),
                ('broadcast', models.CharField(max_length=32, verbose_name='broadcast')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server', verbose_name='主机')),
            ],
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.CharField(max_length=255, verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(max_length=255, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='pd_type',
            field=models.CharField(max_length=255, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.CharField(max_length=32, verbose_name='槽位'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='model',
            field=models.CharField(max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='sn',
            field=models.CharField(max_length=255, verbose_name='sn'),
        ),
    ]
