# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191116_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='cache_size',
            new_name='cachesize',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='clflush_size',
            new_name='clflushsize',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='cpu_cores',
            new_name='cpucores',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='cpu_family',
            new_name='cpufamily',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='model',
        ),
        migrations.AddField(
            model_name='cpu',
            name='modelname',
            field=models.CharField(default='aa', max_length=255, verbose_name='model_name'),
        ),
    ]
