# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-16 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191116_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='cachesize',
            new_name='cache_size',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='clflushsize',
            new_name='clflush_size',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='cpucores',
            new_name='cpu_cores',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='cpufamily',
            new_name='cpu_family',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='modelname',
            new_name='model_name',
        ),
    ]
