# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20191104_1816'),
        ('app01', '0002_auto_20191104_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rbac.Role', verbose_name='职位'),
        ),
    ]
