# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='users',
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='用户名'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
