# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20191106_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.IntegerField(unique=True, verbose_name='分类值'),
        ),
    ]
