# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_permission_role_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
