# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_customer_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
                ('weight', models.IntegerField(default=100)),
            ],
        ),


        migrations.AddField(
            model_name='permission',
            name='menus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Menu'),
        ),
    ]
