# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-29 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191029_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='icon',
        ),
        migrations.AddField(
            model_name='permission',
            name='url_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
