# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-10-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0003_auto_20191019_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
